### ISSUE TITLE
Error in sample_collection_code.py

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/metadatastore#51]
Currently on master branch. Ran sample_collection_code.py and get the following error:

```
Traceback (most recent call last):
File "/home/edill/dev/python/metadataStore/example/sample_collection_code.py", line 71, in <module>
create_event(event)
File "/home/edill/dev/python/metadataStore/metadataStore/collectionapi/commands.py", line 106, in create_event
owner=owner, data=data)
File "/home/edill/dev/python/metadataStore/metadataStore/dataapi/commands.py", line 271, in insert_event
__validate_keys(formatted_data_keys, desc_data_keys)
File "/home/edill/dev/python/metadataStore/metadataStore/dataapi/commands.py", line 293, in __validate_keys
raise ValueError('Data keys for event data and descriptor data do not match! Check ' + str(key))
ValueError: Data keys for event data and descriptor data do not match! Check some_motor_1

Process finished with exit code 1 
```

**Comment by ghost** [comment]
Commit bd30bed46ee5231fe3a96d42f3af3de7ac53a50c fixes this and all related issues that occur in event data value fields.
